admin:
    resource: "@AdminBundle/Controller/"
    type:     annotation
    prefix:   /



destiny_final:
    resource: "@DestinyFinalBundle/Controller/"
    type:     annotation
    prefix:   /



# app/config/routing.yml
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
app:
    resource: '@AppBundle/Controller/'
    type: annotation
